export const categoryList = [
   { name: 'General' },
   { name: 'Salud' },
   { name: 'Belleza' },
   { name: 'Bebés' },
   { name: 'Piel' },
   { name: 'Aseo' },
   { name: 'Malestares' },
   { name: 'Aplicación' },
   { name: 'Ánimo' },
   { name: 'Negocio' },
   { name: 'Niveles' },
];

export const oilsList = [
   { name: 'Abeto de Vancouver' },
   { name: 'Albahaca' },
   { name: 'Alcanforero' },
   { name: 'Alcaravea' },
   { name: 'Angelica' },
   { name: 'Árbol de té' },
   { name: 'Bergamota' },
   { name: 'Canela' },
   { name: 'Cassia' },
   { name: 'Cedro' },
   { name: 'Ciprés' },
   { name: 'Citronela' },
   { name: 'Clavo' },
   { name: 'Copaiba' },
   { name: 'Davana' },
   { name: 'Dorado Azul' },
   { name: 'Elemi' },
   { name: 'Enebro' },
   { name: 'Eneldo' },
   { name: 'Esclarea' },
   { name: 'Eucalipto azul' },
   { name: 'Eucalyptus Globulus' },
   { name: 'Eucalyptus Radiata' },
   { name: 'Gaulteria' },
   { name: 'Geranio' },
   { name: 'Geranium Bourbon' },
   { name: 'Goldenrod' },
   { name: 'Helicriso' },
   { name: 'Hierbabuena' },
   { name: 'Hinojo' },
   { name: 'Hinoki' },
   { name: 'Hong' },
   { name: 'Incienso' },
   { name: 'Incienso sagrado' },
   { name: 'Jara' },
   { name: 'Jazmín' },
   { name: 'Jengibre' },
   { name: 'Kunzea' },
   { name: 'Lavanda' },
   { name: 'Ledum' },
   { name: 'Lima' },
   { name: 'Limón' },
   { name: 'Limón de jade' },
   { name: 'Mandarina' },
   { name: 'Manzanilla' },
   { name: 'Matricaria' },
   { name: 'Mejorana' },
   { name: 'Melisa' },
   { name: 'Menta' },
   { name: 'Mirra' },
   { name: 'Mirto' },
   { name: 'Mirto limón' },
   { name: 'Naranja' },
   { name: 'Neroli' },
   { name: 'Nuez moscada' },
   { name: 'Ocotea' },
   { name: 'Orégano' },
   { name: 'Pachulí' },
   { name: 'Palo Santo' },
   { name: 'Pasto de limón' },
   { name: 'Pícea azul de Idaho' },
   { name: 'Pícea negra Northern Lights' },
   { name: 'Pimienta negra' },
   { name: 'Pino' },
   { name: 'Pomelo' },
   { name: 'Romero' },
   { name: 'Rosa' },
   { name: 'Rue' },
   { name: 'Salvia' },
   { name: 'Sándalo Real Hawaiano' },
   { name: 'Sándalo sagrado' },
   { name: 'Semilla de zahahoria' },
   { name: 'Tanaceto azul' },
   { name: 'Tomillo' },
   { name: 'Vainilla' },
   { name: 'Valeriana' },
   { name: 'Vetiver' },
   { name: 'Xiang Mao' },
   { name: 'Ylang Ylang' },
];

/* export const oilsList = [
   'Abeto de Vancouver',
   'Albahaca',
   'Alcanforero',
   'Alcaravea',
   'Angelica',
   'Árbol de té',
   'Bergamota',
   'Canela',
   'Cassia',
   'Cedro',
   'Ciprés',
   'Citronela',
   'Clavo',
   'Copaiba',
   'Davana',
   'Dorado Azul',
   'Elemi',
   'Enebro',
   'Eneldo',
   'Esclarea',
   'Eucalipto azul',
   'Eucalyptus Globulus',
   'Eucalyptus Radiata',
   'Gaulteria',
   'Geranio',
   'Geranium Bourbon',
   'Goldenrod',
   'Helicriso',
   'Hierbabuena',
   'Hinojo',
   'Hinoki',
   'Hong',
   'Incienso',
   'Incienso sagrado',
   'Jara',
   'Jazmín',
   'Jengibre',
   'Kunzea',
   'Lavanda',
   'Ledum',
   'Lima',
   'Limón',
   'Limón de jade',
   'Mandarina',
   'Manzanilla',
   'Matricaria',
   'Mejorana',
   'Melisa',
   'Menta',
   'Mirra',
   'Mirto',
   'Mirto limón',
   'Naranja',
   'Neroli',
   'Nuez moscada',
   'Ocotea',
   'Orégano',
   'Pachulí',
   'Palo Santo',
   'Pasto de limón',
   'Pícea azul de Idaho',
   'Pícea negra Northern Lights',
   'Pimienta negra',
   'Pino',
   'Pomelo',
   'Romero',
   'Rosa',
   'Rue',
   'Salvia',
   'Sándalo Real Hawaiano',
   'Sándalo sagrado',
   'Semilla de zahahoria',
   'Tanaceto azul',
   'Tomillo',
   'Vainilla',
   'Valeriana',
   'Vetiver',
   'Xiang Mao',
   'Ylang Ylang',
];
 */

/* export const categoryList = [
   'general',
   'salud',
   'belleza',
   'bebés',
   'piel',
   'aseo',
   'malestares',
   'aplicación',
   'ánimo',
   'negocio',
   'niveles',
];
*/
